#common configuration shared between all applications
configserver:
    name: Docker JHipster Registry
    status: Connected to the JHipster Registry running in Docker

jhipster:
    security:
        authentication:
            jwt:
                base64-secret: ZTM0YjFkNTAwMWU0Y2JkNzlhMmJjZWVkNTZhNWNiMDYzMDVhMzgzM2Y1MTkwYzQ5NTIyNTFmMDM0NDY5MzM0MWIwMjQyN2FhMWJkOGY2NTQ5YmQ3NGMzM2ZjYzUwOTVhZTgzODQyMTc4YjU3ODA3OGUzZmZhM2U5NjE0OGNkNDA=

eureka:
    client:
        service-url:
            defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
